apiVersion: v1
kind: Service
metadata:
  name: angular-miyembro
spec:
  selector:
    app: angular-miyembro
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30055
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-miyembro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-miyembro
  template:
    metadata:
      labels:
        app: angular-miyembro
    spec:
      containers:
        - name: angular-miyembro
          image: ${REPOSITORY_TAG}
          ports:
            - containerPort: 80