version: '3.8'

services:
  angular-app:
    image: ${DOCKERHUB_USERNAME}/angular-miyembro:latest
    networks:
      - miyembro-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - API_URL=http://gateway-service:8222
    depends_on:
      - gateway-service

networks:
  miyembro-network:
    external: true