export enum EventFormType {
    ADD_EVENT = 'ADD_EVENT',
    UPDATE_EVENT = 'UPDATE_EVENT',
    UPDATE_EVENT_CONTACT_DETAILS = 'UPDATE_EVENT_CONTACT_DETAILS',
    UPDATE_EVENT_DESCRIPTION = 'UPDATE_EVENT_DESCRIPTION'
}
  