export enum OrganizationFormType {
    ADD_ORGANIZATION = 'ADD_ORGANIZATION',
    UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',
    UPDATE_ORGANIZATION_CONTACT_DETAILS = 'UPDATE_ORGANIZATION_CONTACT_DETAILS',
    UPDATE_ORGANIZATION_DESCRIPTION = 'UPDATE_ORGANIZATION_DESCRIPTION'


}
  